### ISSUE TITLE
Bundling Error

### ISSUE THREAD

**Issue by Jastor11** [rynobax/react-native-plotly#18]
Just tried the package out and am getting the following error when trying out your example:

```
Error: Unable to resolve module `react-native-webview` from `node_modules/react-native-plotly/dist/plotly.js`: 
react-native-webview could not be found within the project.
```

Should that be fixed or am I missing something else here?

**Comment by Jastor11** [comment]
Also, in your examples/basic/node_modules/react-native-plotly folder, there is an additional node modules folder - which seems to be why your example worked when I forked the project and ran it locally.

However, when I ran `npm install --save react-native-plotly` in my own project, no node_modules were included with the react-native-plotly package.

Definitely could be an oversight on my part, but I'm checking to make sure I've handled things correctly.

**Comment by rynobax** [comment]
Try running `expo install react-native-webview` if you have expo cli, otherwise you can try `npm install react-native-webview`.  It looks like it is missing from the example dependencies.

**Comment by Jastor11** [comment]
Bug on my end. Got everything working. Thanks.

**Comment by ManuelZ** [comment]
Thanks, this solved it for me.

Thanks for open-sourcing your project @rynobax !!
