### ISSUE TITLE
Add support for full plotly.js bundle

### ISSUE THREAD

**Issue by rynobax** [rynobax/react-native-plotly#2]
Right now this library is using the [basic bundle](https://github.com/plotly/plotly.js/blob/master/dist/README.md#plotlyjs-basic).  When I try to use the full bundle, an error occurs.

**Comment by nirjack** [comment]
whats the error when you try to use full bundle?

**Comment by nirjack** [comment]
whats the error? I can help you in fixing it!

**Comment by rynobax** [comment]
It's been a while so I don't remember exactly what the error was.  If you want to investigate, you should be able to clone this repo and run the app in the `/examples` directory.  Then in `src/plotly.tsx` you can change the import from `./lib/PlotlyBasic` to `./lib/PlotlyFull`.

**Comment by nirjack** [comment]
Great, Thank you

**Comment by mxfeinberg** [comment]
@rynobax  Has any progress been made on this front?  Could you walk me through the process of trying to add another sub-component of Plotly?

Specifically, I'm looking to add the plotly.js finance components.

Thank you again for your help!

**Comment by mxfeinberg** [comment]
@rynobax I was able to use your getPlotly script to download the finance components and I then modified plotly.tsx to point to the new PlotlyFinance library.  It's working just as expected.

**Comment by rynobax** [comment]
Nice.  I think the issue with the full bundle was related to the size of it, so I can see if I can include some of the smaller bundles like finance in this library.

**Comment by rynobax** [comment]
So I tried the full bundle again on the latest version of React Native, and it worked fine.  I'm guessing something about the WebView implementation changed and the old issue is gone.

I added a new prop `enableFullPlotly` that will load the full bundle instead of the basic bundle, so finance plots should work.  I want to test this on some devices before doing a full release, but you should be able to install it using the beta version `1.0.0-0`.  Let me know if it works for you!

(I also changed the default style in that release, see [the changelog](https://github.com/rynobax/react-native-plotly/blob/master/CHANGELOG.md) for details.  Your chart might disappear 😄)
