### ISSUE TITLE
Graph not updating properly when data length changes

### ISSUE THREAD

**Issue by jherman3** [rynobax/react-native-plotly#24]
I'm using this library to plot some data and sometimes I will update the data prop to an array that is a different size than the previous state. Each time I'm passing a new array (the data is not being modified in-place). 
When the new array is longer than the previous one, only the first part of the array is graphed, and when the new array is shorter, the graph does not delete the extra elements. This seems to be due to how `getDiff` is implemented.  
Is this usecase supported or is the intention to manually use the update functions?

**Comment by rynobax** [comment]
That sounds like a bug.  You should be able to fix it by providing your own update function, and I will take a look at fixing the default update implementation.

**Comment by rynobax** [comment]
Fixed in #26
