### ISSUE TITLE
Rangeslider don't interact

### ISSUE THREAD

**Issue by Gogn** [rynobax/react-native-plotly#27]
Hello, I try to use **react-native-plotly** with **react-native/Expo**:
"react": "~16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
"expo": "^36.0.2",

A charts working well, but prior function that I need is range slider. I try to add it like here: https://plotly.com/javascript/range-slider/#basic-range-slider-on-time-series

_xaxis: {
            rangeselector: selectorOptions,
            rangeslider: {}
        },_

Range appear under chart, but not respond to interact (touches, swipes). Either in the emulator or on the phone (Android).

I try **enableFullPlotly={true}** option but no luck.

How can **rangeslider** should be configured correctly and can it be responsive to touches?
![X1v2KEt](https://user-images.githubusercontent.com/1881637/79023303-07d38b00-7b91-11ea-81b8-cdd8f43fb7c2.png)

**Comment by rynobax** [comment]
I believe this is an issue with Plotly on mobile, not with this library.  See https://github.com/plotly/plotly.js/issues/1098
