### ISSUE TITLE
When used inside a ScrollView webview is not visible. 

### ISSUE THREAD

**Issue by sidtagirisa** [rynobax/react-native-plotly#3]
Can you look at https://www.npmjs.com/package/react-native-auto-expanding-webview and implement with that or can you suggest some solution for my use case. 
<ScrollView><PieChart ... /></ScrollView>

**Comment by aurelio4** [comment]
Hey I'm having this same problem right now, whenever I use <Plotly /> inside of any view it doesn't show. Did you happen to find a fix for this?
