### ISSUE TITLE
does it draw 3d graph

### ISSUE THREAD

**Issue by hungdev** [rynobax/react-native-plotly#36]
Thank for your library. @rynobax 
does it draw 3d graph?
like this:
https://plotly.com/javascript/3d-point-clustering/
I tried to draw 3d graph, but it seems doesn't work. Maybe my code is wrong.
please give me example draw 3d graph like this https://plotly.com/javascript/3d-point-clustering/
thank you so much

**Comment by rynobax** [comment]
It should work, you might need to set the `enableFullPlotly` prop to true.

**Comment by hungdev** [comment]
Thank you, it worked with `enableFullPlotly`
