### ISSUE TITLE
White Screen Issue

### ISSUE THREAD

**Issue by mxfeinberg** [rynobax/react-native-plotly#4]
Hello @rynobax ,

I am currently in the process of converting an R-Shiny application to React-Native and I was attempting to use this package as all of the R plots used plotly.  I am new to react-native so please pardon my ignorance.  I have successfully installed the package and I have followed the example and integrated it into my application.  However, whenever I include the <Plotly/> tag, many of the other elements in the given app page don't seem to load or are covered (?).  Specifically, text and image elements do not appear and neither does the plotly plot.

No errors appear, the majority of the app just appears blank.  Have you encountered this problem before?  Do you have any tips on debugging this issue?

**Comment by rynobax** [comment]
It's hard to say without looking at any code.  I would make sure you set the `debug` prop to true, as that will show additional information.  You could also try changing the background color of the plot to see where the plot is being rendered (the default color is white).

**Comment by mxfeinberg** [comment]
@rynobax Thank you for the quick reply!  I switched the background color to black and I'm still not seeing anything.  To test the package, I made a new app with create-react-native-app and I chose the preset option with tabs.  I then added the below code
`const data = {
    x: [1, 2, 3, 4, 5],
    y: [1, 2, 3, 4, 8],
    type: 'scatter',
  };
  const layout = { title: 'My cool chart!',
                             plot_bgcolor: 'black' };` 
to the HomeScreen Function and 
`<Plotly
  data={data}
  layout={layout}
  debug={true}
/> ` to the return literal.  I experienced the same bug in the primary app that was I developing.  If it helps, I am developing on an Ubuntu 16.04 machine.  The white screen issue occurs on the android simulator and on iOS, the app renders properly but without any plot.

**Comment by mxfeinberg** [comment]
@rynobax do you have an example app I could try on my system?

**Comment by mxfeinberg** [comment]
One more update, so I got the plotly graph to render but it's not actually plotting anything.  Here is what my component looks like.

`

import React from 'react';
import Plotly from 'react-native-plotly';

class ValuePlot extends React.Component {
  
  constructor(props) {
    super(props);
    this.state = {
      data: {x: [1, 2, 3, 4, 5],
             y: [1, 2, 3, 4, 8],
             type: 'scatter'},
      layout: {
         title: 'My cool chart!',
         plot_bgcolor: 'black'  
      }
    }
    console.log(this.state.data)
  }
  render() {
  return (
    <Plotly
      data={this.state.data}
      layout={this.state.layout}
    />
  )
}
}
export default ValuePlot

`

And the component is used like this.

`render() {
    const dimensions = Dimensions.get('window');

    return (
        <View style={{flex: 1,
                      width: "50%"}}>
        <ValuePlot/>
        </View>
    );
 }`

**Comment by rynobax** [comment]
Thanks for the info.  It looks right to me.  Tomorrow I'll try to get a repo up with an up to date example that you can try to run.  What version of react native are you using?

**Comment by rynobax** [comment]
So I looked into it today, and was able to get the chart to show up on RN version 0.59.  I made an example that works for me: https://github.com/rynobax/react-native-plotly-demo .  Give that a try and let me know if it works.

**Comment by mxfeinberg** [comment]
It turned out that it was just an issue with the views that I was using to house the plot. Thank you for your help!
