### ISSUE TITLE
it still be maintained?

### ISSUE THREAD

**Issue by reberthkss** [rynobax/react-native-plotly#48]
Hey guys, I've a silly question: is this library keep maintained yet?

**Comment by rynobax** [comment]
I still keep an eye on the issues for this repo, but I am not actively working on features.  AFAIK it should still work, but the version of plotly might be a bit outdated.  I'll try to publish a version with a newer version of plotly soon.  The code is very simple, so it should be easy to fork it if you want to make some changes if you want to just do that.

**Comment by reberthkss** [comment]
@rynobax ok, I'll check soon

**Comment by yinshurman** [comment]
very expect new release !!!

**Comment by bklingen** [comment]
If you have time to update to the latest plotly version, e.g., 2.8.0, this would be fantastic.

**Comment by rynobax** [comment]
> If you have time to update to the latest plotly version, e.g., 2.8.0, this would be fantastic.

just released version `6.0.0` that includes plotly v2.8.1

**Comment by bklingen** [comment]
Thank you very much!
