### ISSUE TITLE
Expose onLoad callback to Plotly element

### ISSUE THREAD

**Issue by BatchOfCookies12** [rynobax/react-native-plotly#5]
I noticed there is an onLoad for the webview within the Plotly component as well as a function that performs the plotly loading. Is there any way we could have one or both of these exposed as props so that I can indicate to my users when the component is loading a chart?

**Comment by rynobax** [comment]
Yeah, I'll look into this

**Comment by rynobax** [comment]
This will be added in the next release!  It needs more testing first, but you can try it out now using the beta version 1.0.0-0. Let me know if it works for you!

(I also changed the default style in that release, see [the changelog](https://github.com/rynobax/react-native-plotly/blob/master/CHANGELOG.md) for details. Your chart might disappear 😄)

**Comment by matthaidet** [comment]
Thanks for adding this, I'll give it a try!
